version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sport-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "testA111a111a11", "-C", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mssql_data:/var/opt/mssql

  backend:
    build:
      context: ./sport-calendar-backend
      dockerfile: Dockerfile
    container_name: sport-backend
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DbContext=${DB_CONNECTION}
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./sport-calendar-frontend
      dockerfile: Dockerfile
    container_name: sport-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  mssql_data: